// <auto-generated />
using System;
using CURSO_FUNDAMENTOS_EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CURSO_FUNDAMENTOS_EF.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20230308225120_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CURSO_FUNDAMENTOS_EF.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("e9786fb9-0b5a-4e0a-b181-0265123d1e2e"),
                            Nombre = "Actividades pendientes",
                            Peso = 2
                        },
                        new
                        {
                            CategoriaId = new Guid("ac8e7b88-ba94-4525-a2d3-b91afb7b9968"),
                            Nombre = "Actividades personales",
                            Peso = 30
                        },
                        new
                        {
                            CategoriaId = new Guid("16380453-22c4-4971-98f3-20404321d976"),
                            Nombre = "Actividades terminadas",
                            Peso = 12
                        });
                });

            modelBuilder.Entity("CURSO_FUNDAMENTOS_EF.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("4c175dee-3cc8-4b85-be90-2d5c4f296557"),
                            CategoriaId = new Guid("e9786fb9-0b5a-4e0a-b181-0265123d1e2e"),
                            FechaCreacion = new DateTime(2023, 3, 8, 19, 51, 20, 4, DateTimeKind.Local).AddTicks(358),
                            PrioridadTarea = 1,
                            Titulo = "Pago de servicios publicos"
                        },
                        new
                        {
                            TareaId = new Guid("51a0aa6d-b01d-4100-bec1-9f91ed98ec30"),
                            CategoriaId = new Guid("ac8e7b88-ba94-4525-a2d3-b91afb7b9968"),
                            FechaCreacion = new DateTime(2023, 3, 8, 19, 51, 20, 4, DateTimeKind.Local).AddTicks(370),
                            PrioridadTarea = 2,
                            Titulo = "Terminar curso ASP.NET"
                        });
                });

            modelBuilder.Entity("CURSO_FUNDAMENTOS_EF.Models.Tarea", b =>
                {
                    b.HasOne("CURSO_FUNDAMENTOS_EF.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CURSO_FUNDAMENTOS_EF.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
